### ISSUE TITLE
功能请求：记忆「按键显示」状态，在重启时恢复状态

### ISSUE THREAD

**Issue by pilgrimlyieu** [pattazl/showKeyBoard#1]
非常好的软件！一开始用的是 [WhatPulse](https://whatpulse.org)，但这个软件会上传数据，同时部分功能需要会员，然后就去用 [KMCounter](https://github.com/telppa/KMCounter) 了。但是这个软件比较简陋，高分屏下按键字符比较小，而且统计数据也不太直观。昨天才发现这个软件。

但是有几点建议和问题反馈，不知道放在一个 issue 里会不会不太好，如果有需要的话我可以拆分到几个 issue 里。

## 功能请求

- [x] 希望能增加记忆「按键显示」状态的功能。按键显示固然非常有用，但平时我只需要进行统计，并不需要显示按键。实在需要显示按键也可以通过热键进行启动。但是目前的状况是，我关闭了按键显示，重启程序后又会自动打开按键显示，需要我手动进行关闭。因此我希望能加入记忆上次按键显示状态的功能。
- [ ] 希望能增加像 WhatPulse 一样的鼠标点击的屏幕热力图功能。
- [x] 希望能增加像 WhatPulse 一样的统计不同程序的按键与鼠标数量的功能。
- [x] ~~希望能增加像 WhatPulse 一样统计不同组合键，如 <kbd>Ctrl</kbd> + <kbd>C</kbd> 的数目的功能~~啊我看到了，就在数据统计下面。不过能不能将左右合并显示，比如 <kbd>LCtrl</kbd> 和 <kbd>RCtrl</kbd> 都视为 <kbd>Ctrl</kbd>？
- [ ] 「数据统计」里的相同键盘按键能否进行合并？

## 问题反馈

- [x] 「参数设置」里的「按键临时显示开关快捷键」似乎无法设置部分按键？比如我设置了「#^+s」，但是配置文件里却是「\\#^+s」，如果我手动改为了正确的热键，「参数设置」里显示为空。
- [x] 「参数设置」里背景色及字体颜色设置有时候会出现问题，进而保存时出现 AutoHotkey 报错。不过我刚刚对 2. 进行重新测试时，即使我手动更改了热键，仍然会报错，提示 guiOpacity 为 NaN，我将 NaN 恢复为原本数据后重启，背景颜色就发生了变化，从黑色半透明背景变为了深蓝色半透明背景（guiBgcolor 从 000000 变为 080）。但由于我没法完整准确复现，因此只是提一嘴。
- [x] 我的浏览器是深色模式，打开数据统计后也是深色模式，但右上角的按钮显示的也是「深色」，实际上应该是「浅色」。
- [x] RCtrl 显示错误，数据统计组合键列表 RCtrl 显示为 LCtrl。（#2）
- [x] Release 中压缩包包含了 `showKeyBoard.ini` 和 `records.db`，在更新时容易发生覆盖导致设置和数据丢失。

![](https://github.com/pattazl/showKeyBoard/assets/80107081/b92bd2cc-d289-436a-97af-766bb11c9377)
![](https://github.com/pattazl/showKeyBoard/assets/80107081/02f21afd-d4ff-43c7-bb36-f77f0ba19e2b)
![](https://github.com/pattazl/showKeyBoard/assets/80107081/e8b934c4-f5b1-4069-9c6f-a12ab0f883f2)

当然以上可能有部分功能已被实现但我没发现，也请您告知。

最后再次感谢您开发的这个软件！

**Comment by pattazl** [comment]
感谢试用，我近期来一一优化

**Comment by pattazl** [comment]
希望能增加记忆「按键显示」状态的功能。按键显示固然非常有用，但平时我只需要进行统计，并不需要显示按键。实在需要显示按键也可以通过热键进行启动。但是目前的状况是，我关闭了按键显示，重启程序后又会自动打开按键显示，需要我手动进行关闭。因此我希望能加入记忆上次按键显示状态的功能。
// 按键显示 功能本身就是临时的，如果需要关闭按键显示，请在托盘右键菜单的  参数设置 中 配置 “是否显示键盘和鼠标按键 ”关闭，然后保存就可以了。
    希望能增加像 WhatPulse 一样的鼠标点击的屏幕热力图功能。
// 没用过WhatPluse鼠标点击屏幕的热力图，那岂不是要把整个屏幕的坐标的记录下来？数据量是否非常大，还是对屏幕进行了网格处理过？我去研究研究
    希望能增加像 WhatPulse 一样的统计不同程序的按键与鼠标数量的功能。
// 这个建议不错，相当于每次按键的时候都同步记录当前的程序名，不过可能会涉及表重新设计，需要一些时间
    希望能增加像 WhatPulse 一样统计不同组合键，如 Ctrl + C 的数目的功能啊我看到了，就在数据统计下面。不过能不能将左右合并显示，比如 LCtrl 和 RCtrl 都视为 Ctrl？
// 这个可以做，直接在展示的时候进行转换就行了，会在下一个版本中加入
    「数据统计」里的相同键盘按键能否进行合并？
// 如何理解相同键盘按键？

**Comment by pattazl** [comment]
「参数设置」里的「按键临时显示开关快捷键」似乎无法设置部分按键？比如我设置了「#^+s」，但是配置文件里却是「\#^+s」，如果我手动改为了正确的热键，「参数设置」里显示为空。
// 这个的确是个问题，好像是因为#控制键的问题，我来修复

「参数设置」里背景色及字体颜色设置有时候会出现问题，进而保存时出现 AutoHotkey 报错。不过我刚刚对 2. 进行重新测试时，即使我手动更改了热键，仍然会报错，提示 guiOpacity 为 NaN，我将 NaN 恢复为原本数据后重启，背景颜色就发生了变化，从黑色半透明背景变为了深蓝色半透明背景（guiBgcolor 从 000000 变为 080）。但由于我没法完整准确复现，因此只是提一嘴。
// 这个应该是设置颜色没有正确设置的原因，我加点try试试，一般都建议在设置界面中配置颜色，如果能复现，请帮忙告知步骤。

我的浏览器是深色模式，打开数据统计后也是深色模式，但右上角的按钮显示的也是「深色」，实际上应该是「浅色」。
// 这个问题会进行修复

RCtrl 显示错误，数据统计组合键列表 RCtrl 显示为 LCtrl。（
https://github.com/pattazl/showKeyBoard/pull/2）
// 我会近期合并

Release 中压缩包包含了 showKeyBoard.ini 和 records.db，在更新时容易发生覆盖导致设置和数据丢失。
// 我的方案是用 数据处理模块中的 数据导出，导入功能避免被覆盖，暂时没想到更好的方案，因为我的这个软件没有联网，所以不支持自动升级，当然我可以做一个 NSIS安装包，在安装的时候进行提示，但这样就不是绿色软件了，但貌似比现在的直接解压的方案要好一些。

**Comment by pilgrimlyieu** [comment]
> // 这个应该是设置颜色没有正确设置的原因，我加点try试试，一般都建议在设置界面中配置颜色，如果能复现，请帮忙告知步骤。

最新 [V1.13](https://github.com/pattazl/showKeyBoard/releases/tag/1.13) 可以复现，复现步骤：
1. 打开设置，将「背景色和透明度」设置为黑色 `#000000`，透明度似乎无影响。
2. 保存后自动重启，再次打开设置，背景色出现错误。
3. 此时无修改状态下保存自动重启，会弹出 AutoHotkey 的报错，同时背景色也被修改。

> // 我的方案是用 数据处理模块中的 数据导出，导入功能避免被覆盖，暂时没想到更好的方案，因为我的这个软件没有联网，所以不支持自动升级，当然我可以做一个 NSIS安装包，在安装的时候进行提示，但这样就不是绿色软件了，但貌似比现在的直接解压的方案要好一些。

考虑到未来可能会有很多小白使用您的软件，我也比较建议您有一个更好的方案。

**Comment by pattazl** [comment]
> 启动时不开启（或者说记忆上次状态），然后设置的热键可以用来临时开启。
// 这个会考虑加入

> 目前数据统计中比较大的按键，如 Space CapsLock 是以多个小方格拼接的形式呈现的，如果可能的话，以一个整体的矩形显示会不会更美观一点？
// 这个我暂时没找到更好的技术方案，本来是想设计为用户可以自己画HTML，然后自动更新的，但是可能复杂度更高。

> 考虑到未来可能会有很多小白使用您的软件，我也比较希望您有一个更好的方案。
// 那还是抽空我做个NSIS的包

由于平时工作比较忙，业余时间抽空整的，所以就每天修改一点bug，希望可以尽快将此ISSUE的问题都解决

**Comment by pattazl** [comment]
发布了1.14版本，除了以下问题，其他都解决了：
希望能增加像 WhatPulse 一样的鼠标点击的屏幕热力图功能。
希望能增加像 WhatPulse 一样的统计不同程序的按键与鼠标数量的功能。
「数据统计」里的相同键盘按键能否进行合并？

**Comment by pilgrimlyieu** [comment]
> 发布了1.14版本

感谢:heart:，不过我测试了一下，发现设置字体后卡在了保存界面，一直显示数据保存中。是我这里的操作问题吗？不知道您那里能否复现。

![1](https://github.com/pattazl/showKeyBoard/assets/80107081/db9a4ec8-62b1-47b8-8ede-b74b53b4ebee)

**Comment by pattazl** [comment]
的确是还有一些bug，今天晚上争取修复下

**Comment by pattazl** [comment]
1.15已经修复好不能保存的问题，同时对安装包做了大量的优化。
「按键清单」 本身就是自己定义的，只是有个默认清单而已
