### ISSUE TITLE
功能性按键无法取消按键显示

### ISSUE THREAD

**Issue by LanRenLan** [pattazl/showKeyBoard#4]
用shift、alt和Windows键的时候，即使已经关闭了按键显示功能，也会在左上角显示一个窗口
系统是Win11，软件版本v1.27，希望可以修复一下，非常感谢
![image](https://github.com/pattazl/showKeyBoard/assets/112599739/5de1925d-9ee3-4955-aa9f-1dbf5489b892)

**Comment by pattazl** [comment]
功能性按键的显示和管理有额外的一个开关
![图片](https://github.com/pattazl/showKeyBoard/assets/3849200/4e28186f-2548-4a8b-8b01-8ec6c04942dd)
上图的 “是否显示控制键状态” 关闭即可，这个功能主要是用于显示这些特殊按键的状态，防止被卡住还不知道

**Comment by LanRenLan** [comment]
喔噢，非常感谢

AustinYoung ***@***.***> 于2023年12月15日周五 00:38写道：
