### ISSUE TITLE
软件操作疑问 我想请教一个问题如何屏蔽鼠标的滚轮的滑动记录呢

### ISSUE THREAD

**Issue by ty-lab** [pattazl/showKeyBoard#5]
我添加要忽略记录的按键中有“WheelUp、WheelDown”，但是今天数据中仍有滚轮记录

**Comment by pattazl** [comment]
你反馈的问题好像的确存在，应该是bug，估计是加功能不小心给改坏了，我会尽快修复

**Comment by pattazl** [comment]
原因找到了，因为默认的忽略记录是键盘按键的，鼠标是在另外的地方进行控制，程序大概今天晚上更新到 1.30版本解决此问题。

**Comment by pattazl** [comment]
已经更新到1.30，解决了此问题

**Comment by ty-lab** [comment]
麻烦了 谢谢啦
