### ISSUE TITLE
请问后续有考虑增加记录某应用上的按键使用频率吗

### ISSUE THREAD

**Issue by u2003yuge** [pattazl/showKeyBoard#7]

**Comment by pattazl** [comment]
目前已经有针对应用的按键和鼠标统计信息，但是你如果是要某个应用的详细按键信息的话，由于数据量较大，目前是没有根据每个应用分别统计按键的，暂时没有统计某个应用的的功能，如果需要请描述详细场景和需求，我看看如何来实现。
不过，如果只是要在某个应用上显示按键，可以通过 设置 -> 按键显示仅针对活跃窗口 输入对应的进程名来过滤。

**Comment by u2003yuge** [comment]
感谢作者的回复。是想记录每个应用分别统计按键使用情况的，从不同应用的使用情况能看出不同应用的区别，比如游戏的WASD频率会比较多，而文档类的元音使用会比较多····但这么做可能会泄露关键信息（比如密码）

**Comment by pattazl** [comment]
1.35版本已经加入此功能,可以过滤相关的进程,默认不过滤,此问题关闭
